### ISSUE TITLE
Entity Serialization using Jackson annotations are ignored.

### ISSUE THREAD

**Issue by marvfinsy** [kotlin-orm/ktorm#437]
Entity serialization using @JasonFormat annotation for a field does not work. It appears to be ignored. My assumption is that the issue is the fact that the annotation is on an interface and not a standard class. Using just @JasonFormat gave me a "no backing field error". Using @get:JasonFormat eliminated the backing field error but as i described seemed to be ignored and the field serialized ignoring the annotation.

My questions are:

1. Do Jackson Serialization Annotations work on an entity?
2. If they do work do u have an example of usage/how to set it up?
3. If they don't work do u have a solution other than using data classes as described in ur docs.

thx ~Marvin Foster
email: mmarvb7@gmail.com

**Comment by vincentlauvlwj** [comment]
In general, Jackson annotations don't work on a Ktorm entity, because entity is an interface and not standard class just as you said. 

But there are some exceptions, some limited annotations can be recognized by Ktorm's Jackson module, they are `@get:JsonIgnore`, `@get:JsonAlias` and `@get:JsonProperty`. Ktorm's Jackson module can read those annotations and try to perform like Jackson's default behaviour. However, `@JsonFormat` is not included in those annotations. 

So, as a suggestion, it's better to convert your data from Ktorm entity to a normal class, then serialize the normal class instead.

**Comment by marvfinsy** [comment]
thx for the reply...
I basically created a data class that contains just the fields i want and serialize from there. Actually works to better de-couple query responses from db.
thx again...
