### ISSUE TITLE
Postgres bulkInsertOrUpdate should have similar item() parameters as batchInsert

### ISSUE THREAD

**Issue by sigmanil** [kotlin-orm/ktorm#465]
The item() of batchInsert looks like this:
`fun item(block: AssignmentsBuilder.(T) -> Unit)`
 
The item() of bulkInsertOrUpdate in the Postgres module looks like this:
`fun item(block: AssignmentsBuilder.() -> Unit)`

Note the missing "T" type parameter on the block parameter in bulkInsertOrUpdate.

To us, this means the bulkInsertOrUpdate can't be used with the same convenience assignment methods we use for our other insertion methods as the types don't match. A fairly minor annoyance, but it does force us to duplicate some code. Is there a good reason these two methods don't work the same?

**Comment by vincentlauvlwj** [comment]
`T` represents the table object itself. When I first wrote `batchInsert`, I thought it'd be better to narrow down the scopes of closure variables, so I pass the table object to the inner `item` closure instead of `batchInsert`. For example: 

```kotlin
database.batchInsert(Employees) {
    // Cannot acess the table object here
    item {
        // Access the table object via `it`
        set(it.name, "jerry")
    }
}
```

But things changed when I tried to implemennt PostgreSQL's `bulkInsertOrUpdate`, I have to pass the table object to the outer closure, because users need to specify the conflict columnns when using `onConflict`: 

```kotlin
database.bulkInsertOrUpdate(Employees) {
    item {
        // ...
    }
    // Users have to access the table object here.
    onConflict(it.id) {
        set(it.departmentId, excluded(it.departmentId))
        set(it.salary, it.salary + 1000)
    }
}
```

So it is just a historical reason.
